classroom/urls.py
from django.urls import include, path
from django.conf.urls import url
from .views import classroom, students, teachers, fundacion, gestion, jefedepto
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', classroom.home, name='home'),


    path('gestion/', include(([
        path('', gestion.IndexListView.as_view(), name='indexg'),
    ], 'classroom'), namespace='gestion')),

    path('jefedepto/', include(([
        path('', jefedepto.IndexListView.as_view(), name='index'),
        path('quiz/<int:pk>/', jefedepto.change_quiz, name='quiz_edit'),
        path('quiz/<int:pk>/email/', jefedepto.emailView, name='email'),
        path('success/', jefedepto.successView, name='success'),
        path('quiz/<int:pk>/', jefedepto.quiz_info, name='quiz_info'),
        path('quiz/print', jefedepto.categoria_print, name='categoria_print'),
        path('quiz/print/<int:pk>', jefedepto.categoria_print, name='categoria_print_one'),
        url(r'^reporte_personas_pdf/$',jefedepto.ReportePersonasPDF.as_view(), name="reporte_personas_pdf"),
        path('quiz/pdf/<int:pk>', jefedepto.GeneratePdf.as_view(), name='generatepdf'),
        path('quiz/<int:pk>/results/', jefedepto.QuizResultsView.as_view(), name='quiz_results'),

    ], 'classroom'), namespace='jefedepto')),

    path('fundacion/', include(([
        path('', fundacion.IndexListView.as_view(), name='index'),
        path('colegio/add', fundacion.colegio_add , name='colegio_add'),
        path('user_list', fundacion.user_list, name='user_list'),
        path('colegios', fundacion.colegios, name='colegios'),
        path('quiz/<int:pk>/', fundacion.quiz_info, name='quiz_info'),
        url(r'^reporte_personas_excel/$',fundacion.ReportePersonasExcel.as_view(), name="reporte_personas_excel"),
        url(r'^reporte_todos_excel/$',fundacion.ReporteTodosExcel.as_view(), name="reporte_todos_excel"),




    ], 'classroom'), namespace='fundacion')),


    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>', students.quiz_info, name='quiz_info'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),

    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('pregunta/add/', teachers.crear_banco_preguntas, name='crear_banco'),
        path('banco_preguntas/',teachers.banco_preguntas, name='banco_preguntas'),

        path('texto/add',teachers.TextoCreateView.as_view(), name='texto_add'),
        path('texto_list', teachers.texto_creado, name='texto_list'),
        path('texto/<int:pk>/', teachers.TextoUpdateView.as_view(), name='texto_change'),

        path('categoria_creada', teachers.categoria_creada, name='category_list'),
        path('category/add', teachers.category_add , name='category_add'),
        #tabla de especificaciones
        path('planificacion_list/', teachers.PlanificacionListView.as_view(), name='planificacion_list'),
        path('planificacion/', teachers.HomepageView.as_view(), name='planificacion_all'),
        path('planificacion_curso/', teachers.CursoView.as_view(), name='planificacion_curso'),

        ###################################### Lenguaje ############################################
        path('primero/', teachers.PrimeroBView.as_view(), name='primero'),
        path('segundo/', teachers.SegundoBView.as_view(), name='segundo'),
        path('tercero/', teachers.TerceroBView.as_view(), name='tercero'),
        path('cuarto/', teachers.CuartoBView.as_view(), name='cuarto'),
        path('quinto/', teachers.QuintoBView.as_view(), name='quinto'),
        path('sexto/', teachers.SextoBView.as_view(), name='sexto'),
        path('septimo/', teachers.SeptimoBView.as_view(), name='septimo'),
        path('octavo/', teachers.OctavoBView.as_view(), name='octavo'),
        path('planificacion_primero/', teachers.PrimeroMView.as_view(), name='planificacion_primero'),
        path('planificacion_segundo/', teachers.SegundoMView.as_view(), name='planificacion_segundo'),
        path('planificacion_tercero/', teachers.TerceroMView.as_view(), name='planificacion_tercero'),
        ############################################################################################
        ###################################### Matematicas #########################################
        path('primero/', teachers.PrimeroBView.as_view(), name='Mprimero'),
        path('segundo/', teachers.SegundoBView.as_view(), name='Msegundo'),
        path('tercero/', teachers.TerceroBView.as_view(), name='Mtercero'),
        path('cuarto/', teachers.CuartoBView.as_view(), name='Mcuarto'),
        path('quinto/', teachers.QuintoBView.as_view(), name='Mquinto'),
        path('sexto/', teachers.SextoBView.as_view(), name='Msexto'),
        path('septimo/', teachers.SeptimoBView.as_view(), name='Mseptimo'),
        path('octavo/', teachers.OctavoBView.as_view(), name='Moctavo'),
        path('mate_primero/', teachers.MatePrimeroMView.as_view(), name='mate_primero'),
        path('mate_segundo/', teachers.MateSegundoMView.as_view(), name='mate_segundo'),
        path('mate_tercero/', teachers.MateTerceroMView.as_view(), name='mate_tercero'),
        ############################################################################################
        ###################################### Ciencias #########################################
        path('primero/', teachers.PrimeroBView.as_view(), name='Cprimero'),
        path('segundo/', teachers.SegundoBView.as_view(), name='Csegundo'),
        path('tercero/', teachers.TerceroBView.as_view(), name='Ctercero'),
        path('cuarto/', teachers.CuartoBView.as_view(), name='Ccuarto'),
        path('quinto/', teachers.QuintoBView.as_view(), name='Cquinto'),
        path('sexto/', teachers.SextoBView.as_view(), name='Csexto'),
        path('septimo/', teachers.SeptimoBView.as_view(), name='Cseptimo'),
        path('octavo/', teachers.OctavoBView.as_view(), name='Coctavo'),
        path('ciencias_primero/', teachers.CienciasPrimeroMView.as_view(), name='ciencias_primero'),
        path('ciencias_segundo/', teachers.CienciasSegundoMView.as_view(), name='ciencias_segundo'),
        path('ciencias_tercero/', teachers.CienciasTerceroMView.as_view(), name='ciencias_tercero'),
        ############################################################################################
        ####################################### Ingles #########################################
        path('primero/', teachers.PrimeroBView.as_view(), name='Iprimero'),
        path('segundo/', teachers.SegundoBView.as_view(), name='Isegundo'),
        path('tercero/', teachers.TerceroBView.as_view(), name='Itercero'),
        path('cuarto/', teachers.CuartoBView.as_view(), name='Icuarto'),
        path('quinto/', teachers.QuintoBView.as_view(), name='Iquinto'),
        path('sexto/', teachers.SextoBView.as_view(), name='Isexto'),
        path('septimo/', teachers.SeptimoBView.as_view(), name='Iseptimo'),
        path('octavo/', teachers.OctavoBView.as_view(), name='Ioctavo'),
        path('ingles_primero/', teachers.InglesPrimeroMView.as_view(), name='ingles_primero'),
        path('ingles_segundo/', teachers.InglesSegundoMView.as_view(), name='ingles_segundo'),
        path('ingles_tercero/', teachers.InglesTerceroMView.as_view(), name='ingles_tercero'),
        ############################################################################################
        path('planificacion_ciencias/', teachers.CienciasView.as_view(), name='planificacion_ciencias'),
        path('planificacion_ingles/', teachers.InglesView.as_view(), name='planificacion_ingles'),
        path('planificacion/<int:pk>/results', teachers.PlanificacionDetailView.as_view(), name='planificacion_detail'),
        path('planificacion/add/', teachers.PlanificacionCreateView.as_view(), name='planificacion_add'),
        path('planificacion/<int:pk>/', teachers.PlanificacionUpdateView.as_view(), name='planificacion_change'),
        path('planificacion/delete/<int:pk>/', teachers.PlanificacionDelete.as_view(), name='planificacion_delete'),
        #end

        path('', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('ajax/load-indi/', teachers.load_indi, name='ajax_load_indi'),
        path('quiz/<int:quiz_pk>/student/', teachers.student, name='student'),
        path('quiz/pdf/<int:pk>', teachers.GeneratePdf.as_view(), name='generatepdf'),
        path('quiz/<int:pk>/mail/', teachers.mail, name='mail'),
        path('quiz/<int:pk>/send/', teachers.send, name='send'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/chart_data/', teachers.chart_data, name='chart_data'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('quiz/<int:pk>/tfquestion/add/', teachers.tfquestion_add, name='tfquestion_add'),
        path('quiz/<int:quiz_pk>/tfquestion/<int:tfquestion_pk>/', teachers.tfquestion_change, name='tfquestion_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
        path('quiz/<int:quiz_pk>/tfquestion/<int:tfquestion_pk>/delete/', teachers.TFQuestionDeleteView.as_view(), name='tfquestion_delete'),

django_school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.conf.urls import url

from django.contrib import admin
from classroom.views import classroom, students, teachers, fundacion, gestion, jefedepto

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classroom.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('accounts/signup/fundacion/', fundacion.FundacionSignUpView.as_view(), name='fundacion_signup'),
    path('accounts/signup/gestion/', gestion.GestionSignUpView.as_view(), name='gestion_signup'),
    path('accounts/signup/jefedepto/', jefedepto.JefeDSignUpView.as_view(), name='jefedepto_signup'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import (TemplateView,CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response


from django.views.defaults import page_not_found
 



class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:quiz_change_list')
        if request.user.is_student:
            return redirect('students:quiz_list')
        if request.user.is_fundacion:
            return redirect('fundacion:index')
        if request.user.is_jefedepto:
            return redirect('jefedepto:index')
        else:
            return redirect('gestion:indexg')
    return render(request, 'classroom/home.html')







  

classroom/views/gestion.py
import json
import traceback
from itertools import chain
from .__init__ import *
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import get_template,render_to_string
from django.utils.html import strip_tags
from django.template import Context
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.http import JsonResponse,HttpResponse, HttpResponseRedirect
from rest_framework.views import APIView
from rest_framework.response import Response
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from ..decorators import gestion_required
from ..forms import BaseAnswerInlineFormSet,QuestionForm, GestionSignUpForm,  CategoryForm, ColegioForm
from ..models import Answer, Question, Quiz, User, TakenQuiz, StudentAnswer, Category,  Colegios





class GestionSignUpView(CreateView):
    model = User
    form_class = GestionSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'gestion'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('gestion:indexg')


@method_decorator([login_required, gestion_required], name='dispatch')
class IndexListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'classroom/gestion/indexg.html'

    def get_queryset(self):
        gestion = self.request.user.gestion
        gestion_interests = gestion.interests.values_list('pk', flat=True)
        gestion_curso = gestion.curso.values_list('pk', flat=True)
        gestion_colegio = gestion.colegio.values_list('pk', flat=True)
        taken_quizzes = gestion.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.filter(curso__in=gestion_curso, subject__in=gestion_interests, colegio__in=gestion_colegio) \
            .exclude(pk__in=taken_quizzes) 
        return queryset

classroom/templates/classroom/jefedepto/chart_data.html
{% extends 'base.html' %}
{% load static %}

{% block content %}





  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'jefedepto:index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'jefedepto:quiz_info' quiz.pk %}">{{ quiz.name }}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'jefedepto:quiz_results' quiz.pk %}">Resultados</a></li>

        <li class="breadcrumb-item active" aria-current="page">Estadísticas</li>
    </ol>
  </nav>
<br>
<div >
  {% if quiz.colegio.imagen %}
  <img src=" {{ quiz.colegio.imagen.url }} " class="img-fluid" style="float: right;"/>
  {% endif %} 
  <h2 class="mb-3"><strong>{{quiz.name}} </strong> Estadísticas</h2>
      

</div>

<br>

<br> 


  <div class="card mb-3">
      <div class="card-head mb-3">
          <span class="badge badge-primary mb-3">Nota más alta: {{maximo.max}}</span>
          <span class="badge badge-danger mb-3">Nota más baja: {{minimo.min}}</span>
          <span class="badge badge-warning mb-3">Porcentaje aprobación: {{quiz.porcen_pro}}%</span>
          <span class="badge badge-info mb-3">Puntaje total: {{quiz.max_score}} puntos</span>
          <p class="badge badge-success mb-3">Puntaje de aprobación: {{puntaje_aprobacion}} </p>
          <p>Total respuestas: {{studentcount}}</p>
          <span class="badge badge-primary mb-3">Aprobados: {{studentcounta}} </span>
          <span class="badge badge-danger mb-3">Reprobados: {{studentcountr}} </span>
          
          <p>  </p>
      </div>
  </div>



  




    <br>
    <div class="card mb-3">
        <div class="card-header mb-3">

            <h3 class="text-center">Gráfico de porcentaje</h3>

        </div>

            <canvas id="myChart2"></canvas>

        <br>

        <div class="card-header mb-3">

            <h3 class="text-center">Gráfico de porcentaje de Alumnos aprobados y Alumnos reprobados</h3>
            
        </div>

            <canvas id="pieChart" width=400 height=180></canvas>

        <br>

    </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js" integrity="sha256-o8aByMEvaNTcBsw94EfRLbBrJBI+c3mjna/j4LrfyJ8=" crossorigin="anonymous"></script>    

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
    var ctx = document.getElementById('myChart2').getContext('2d');
    var myChart2 = new Chart(ctx, {
        type: 'horizontalBar',
        data: {
            labels: [  {% for question in question %} '{{question.indicador}}', {% endfor %} ],
            datasets: [{
                label: 'Alumnos que lograron el indicador',
                data: [{% for studentcorrecta in studentcorrecta %} '{{studentcorrecta.count}}', {% endfor %}],
                
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',

                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                ],
                borderWidth: 2
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
</script>
  


<script>

  var ctx = document.getElementById('Chart').getContext('2d');
  var Chart = new Chart(ctx, {
      type: 'pie',
      data: {
          labels: ['Alumnos reprobados %','Alumnos aprobados %'],
          datasets: [{
              label: '%',
              data: [  {{porcentaje_reprobados}},{{porcentaje_aprobados}} ],
              backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(54, 162, 235, 0.2)',
                  'rgba(255, 206, 86, 0.2)',
                  'rgba(75, 192, 192, 0.2)',
                  'rgba(153, 102, 255, 0.2)',
                  'rgba(255, 159, 64, 0.2)'
              ],
              borderColor: [
                  'rgba(255, 99, 132, 1)',
                  'rgba(54, 162, 235, 1)',
                  'rgba(255, 206, 86, 1)',
                  'rgba(75, 192, 192, 1)',
                  'rgba(153, 102, 255, 1)',
                  'rgba(255, 159, 64, 1)'
              ],
              borderWidth: 1
          }]
      },
      options: { 
 
      }
  });
  </script>


<script>
var data = {
    datasets: [{
        data: [
           {{porcentaje_aprobados}},{{porcentaje_reprobados}}
        ],
        backgroundColor: [
            "#36A2EB",
            "#FF6384",

            
        ],
        label: 'My dataset' // for legend
    }],
    labels: [
        'Alumnos aprobados ','Alumnos reprobados '
    ]
};

var pieOptions = {
  events: false,
  animation: {
    duration: 500,
    easing: "easeOutQuart",
    onComplete: function () {
      var ctx = this.chart.ctx;
      ctx.font = Chart.helpers.fontString(Chart.defaults.global.defaultFontFamily, 'normal', Chart.defaults.global.defaultFontFamily);
      ctx.textAlign = 'center';
      ctx.textBaseline = 'bottom';

      this.data.datasets.forEach(function (dataset) {

        for (var i = 0; i < dataset.data.length; i++) {
          var model = dataset._meta[Object.keys(dataset._meta)[0]].data[i]._model,
              total = dataset._meta[Object.keys(dataset._meta)[0]].total,
              mid_radius = model.innerRadius + (model.outerRadius - model.innerRadius)/2,
              start_angle = model.startAngle,
              end_angle = model.endAngle,
              mid_angle = start_angle + (end_angle - start_angle)/2;

          var x = mid_radius * Math.cos(mid_angle);
          var y = mid_radius * Math.sin(mid_angle);

          ctx.fillStyle = '#fff';
          if (i == 3){ // Darker text color for lighter background
            ctx.fillStyle = '#444';
          }
          var percent = String(Math.round(dataset.data[i]/total*100)) + "%";
          ctx.fillText(dataset.data[i], model.x + x, model.y + y);
          // Display percent in another line, line break doesn't work for fillText
          ctx.fillText(percent, model.x + x, model.y + y + 15);
        }
      });               
    }
  }
};

var pieChartCanvas = $("#pieChart");
var pieChart = new Chart(pieChartCanvas, {
  type: 'pie', // or doughnut
  data: data,
  options: pieOptions
});
</script>


{% endblock %}

classroom/templates/classroom/jefedepto/email.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags humanize %}
{% block content %}

<nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'jefedepto:index' %}">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'jefedepto:quiz_info' quiz.pk %}">{{ quiz.name }}</a></li>
          <li class="breadcrumb-item active" aria-current="page">Sugerencia</li>
        </ol>
</nav>
<!-- templates/email.html -->
<div class="card">
  <div class="card card-header">
    <h1>Sugerencia de corrección</h1>
  </div>
  <div class="card card-body">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="form-actions">
        <button type="submit" class="btn btn-success">Enviar</button>
      </div>
    </form>
  </div>

</div>
{% endblock %}

classroom/templates/classroom/jefedepto/index.html
{% extends 'base.html' %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Home</li>
    </ol>
  </nav>
  <h2 class="mb-3"><strong>Jefe de Departamento</strong> </h2>
  <br>  
  <p> <strong>Departamento:</strong>  {% for subject in user.jefe_depto.interests.all %}{{subject.get_html_badge}} {% endfor %}</p>
  <br>
  <br>
  <div class="table-responsive table-sm">
    <table id="example" class="table table-bordered ">
      <thead>
        <tr>
          <th>Id</th>
          <th>Profesor</th>
          <th>Colegio</th>
          <th>Curso</th>
          <th>Pruebas creadas</th>
          <th>Creada</th>
          <th></th>

        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td class="align-middle">{{ quiz.owner.first_name }} {{ quiz.owner.last_name }}</td>
            <td class="align-middle">{{ quiz.colegio.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.curso }}{{quiz.nivel}}</td>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle">{{ quiz.created|date:"d/m/y" }}</td>
            
            <td>
              <a href="{% url 'jefedepto:quiz_edit' quiz.pk %}" class="btn btn-primary">Ver examen</a>
              <a href="{% url 'jefedepto:quiz_results' quiz.pk %}" class="btn btn-primary">resultados</a>

            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No hay examenes que puedas tomar en este momento.</td>
          </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

{% endblock %}

classroom/templates/classroom/jefedepto/quiz_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'jefedepto:index' %}">Mis evaluaciones</a></li>
      <li class="breadcrumb-item active" aria-current="page">Añadir una nueva evaluacion</li>
    </ol>
  </nav>
<div class="container-fluid">
  
  {% for colegio in user.jefedepto.colegio.all %}
  <div class="mb-3">
      <p class="mb-3"><img src=" {{ colegio.imagen.url }} " class="img-fluid mb-3" style="width: 18%; float: right;"/></p>

    <h2 class="mb-3">Crear una nueva evaluación</h2>

  </div>

  {% endfor %}
</div>
<br>
  <div class="card">
    <div class="card-body ">
      <div class="row ">
        <div class="col-md-8 col-sm-8 col-12">
          
          <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Guardar</button>
            <a href="{% url 'jefedepto:index' %}" class="btn btn-outline-secondary" role="button">Cancelar</a>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}