classroom/urls.py
from django.urls import include, path
from django.conf.urls import url
from .views import classroom, students, teachers, fundacion, gestion, jefedepto
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', classroom.home, name='home'),


    path('gestion/', include(([
        path('', gestion.IndexListView.as_view(), name='indexg'),
    ], 'classroom'), namespace='gestion')),

    path('jefedepto/', include(([
        path('', jefedepto.IndexListView.as_view(), name='index'),
        path('quiz/<int:pk>/', jefedepto.change_quiz, name='quiz_edit'),
        path('quiz/<int:pk>/email/', jefedepto.emailView, name='email'),
        path('success/', jefedepto.successView, name='success'),
        path('quiz/<int:pk>/', jefedepto.quiz_info, name='quiz_info'),
        path('quiz/print', jefedepto.categoria_print, name='categoria_print'),
        path('quiz/print/<int:pk>', jefedepto.categoria_print, name='categoria_print_one'),
        url(r'^reporte_personas_pdf/$',jefedepto.ReportePersonasPDF.as_view(), name="reporte_personas_pdf"),
        path('quiz/pdf/<int:pk>', jefedepto.GeneratePdf.as_view(), name='generatepdf'),
        path('quiz/<int:pk>/results/', jefedepto.QuizResultsView.as_view(), name='quiz_results'),

    ], 'classroom'), namespace='jefedepto')),

    path('fundacion/', include(([
        path('', fundacion.IndexListView.as_view(), name='index'),
        path('colegio/add', fundacion.colegio_add , name='colegio_add'),
        path('user_list', fundacion.user_list, name='user_list'),
        path('colegios', fundacion.colegios, name='colegios'),
        path('quiz/<int:pk>/', fundacion.quiz_info, name='quiz_info'),
        url(r'^reporte_personas_excel/$',fundacion.ReportePersonasExcel.as_view(), name="reporte_personas_excel"),
        url(r'^reporte_todos_excel/$',fundacion.ReporteTodosExcel.as_view(), name="reporte_todos_excel"),




    ], 'classroom'), namespace='fundacion')),


    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>', students.quiz_info, name='quiz_info'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),

    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('pregunta/add/', teachers.crear_banco_preguntas, name='crear_banco'),
        path('banco_preguntas/',teachers.banco_preguntas, name='banco_preguntas'),

        path('texto/add',teachers.TextoCreateView.as_view(), name='texto_add'),
        path('texto_list', teachers.texto_creado, name='texto_list'),
        path('texto/<int:pk>/', teachers.TextoUpdateView.as_view(), name='texto_change'),

        path('categoria_creada', teachers.categoria_creada, name='category_list'),
        path('category/add', teachers.category_add , name='category_add'),
        #tabla de especificaciones
        path('planificacion_list/', teachers.PlanificacionListView.as_view(), name='planificacion_list'),
        path('planificacion/', teachers.HomepageView.as_view(), name='planificacion_all'),
        path('planificacion_curso/', teachers.CursoView.as_view(), name='planificacion_curso'),

        ###################################### Lenguaje ############################################
        path('primero/', teachers.PrimeroBView.as_view(), name='primero'),
        path('segundo/', teachers.SegundoBView.as_view(), name='segundo'),
        path('tercero/', teachers.TerceroBView.as_view(), name='tercero'),
        path('cuarto/', teachers.CuartoBView.as_view(), name='cuarto'),
        path('quinto/', teachers.QuintoBView.as_view(), name='quinto'),
        path('sexto/', teachers.SextoBView.as_view(), name='sexto'),
        path('septimo/', teachers.SeptimoBView.as_view(), name='septimo'),
        path('octavo/', teachers.OctavoBView.as_view(), name='octavo'),
        path('planificacion_primero/', teachers.PrimeroMView.as_view(), name='planificacion_primero'),
        path('planificacion_segundo/', teachers.SegundoMView.as_view(), name='planificacion_segundo'),
        path('planificacion_tercero/', teachers.TerceroMView.as_view(), name='planificacion_tercero'),
        ############################################################################################
        ###################################### Matematicas #########################################
        path('primero/', teachers.PrimeroBView.as_view(), name='Mprimero'),
        path('segundo/', teachers.SegundoBView.as_view(), name='Msegundo'),
        path('tercero/', teachers.TerceroBView.as_view(), name='Mtercero'),
        path('cuarto/', teachers.CuartoBView.as_view(), name='Mcuarto'),
        path('quinto/', teachers.QuintoBView.as_view(), name='Mquinto'),
        path('sexto/', teachers.SextoBView.as_view(), name='Msexto'),
        path('septimo/', teachers.SeptimoBView.as_view(), name='Mseptimo'),
        path('octavo/', teachers.OctavoBView.as_view(), name='Moctavo'),
        path('mate_primero/', teachers.MatePrimeroMView.as_view(), name='mate_primero'),
        path('mate_segundo/', teachers.MateSegundoMView.as_view(), name='mate_segundo'),
        path('mate_tercero/', teachers.MateTerceroMView.as_view(), name='mate_tercero'),
        ############################################################################################
        ###################################### Ciencias #########################################
        path('primero/', teachers.PrimeroBView.as_view(), name='Cprimero'),
        path('segundo/', teachers.SegundoBView.as_view(), name='Csegundo'),
        path('tercero/', teachers.TerceroBView.as_view(), name='Ctercero'),
        path('cuarto/', teachers.CuartoBView.as_view(), name='Ccuarto'),
        path('quinto/', teachers.QuintoBView.as_view(), name='Cquinto'),
        path('sexto/', teachers.SextoBView.as_view(), name='Csexto'),
        path('septimo/', teachers.SeptimoBView.as_view(), name='Cseptimo'),
        path('octavo/', teachers.OctavoBView.as_view(), name='Coctavo'),
        path('ciencias_primero/', teachers.CienciasPrimeroMView.as_view(), name='ciencias_primero'),
        path('ciencias_segundo/', teachers.CienciasSegundoMView.as_view(), name='ciencias_segundo'),
        path('ciencias_tercero/', teachers.CienciasTerceroMView.as_view(), name='ciencias_tercero'),
        ############################################################################################
        ####################################### Ingles #########################################
        path('primero/', teachers.PrimeroBView.as_view(), name='Iprimero'),
        path('segundo/', teachers.SegundoBView.as_view(), name='Isegundo'),
        path('tercero/', teachers.TerceroBView.as_view(), name='Itercero'),
        path('cuarto/', teachers.CuartoBView.as_view(), name='Icuarto'),
        path('quinto/', teachers.QuintoBView.as_view(), name='Iquinto'),
        path('sexto/', teachers.SextoBView.as_view(), name='Isexto'),
        path('septimo/', teachers.SeptimoBView.as_view(), name='Iseptimo'),
        path('octavo/', teachers.OctavoBView.as_view(), name='Ioctavo'),
        path('ingles_primero/', teachers.InglesPrimeroMView.as_view(), name='ingles_primero'),
        path('ingles_segundo/', teachers.InglesSegundoMView.as_view(), name='ingles_segundo'),
        path('ingles_tercero/', teachers.InglesTerceroMView.as_view(), name='ingles_tercero'),
        ############################################################################################
        path('planificacion_ciencias/', teachers.CienciasView.as_view(), name='planificacion_ciencias'),
        path('planificacion_ingles/', teachers.InglesView.as_view(), name='planificacion_ingles'),
        path('planificacion/<int:pk>/results', teachers.PlanificacionDetailView.as_view(), name='planificacion_detail'),
        path('planificacion/add/', teachers.PlanificacionCreateView.as_view(), name='planificacion_add'),
        path('planificacion/<int:pk>/', teachers.PlanificacionUpdateView.as_view(), name='planificacion_change'),
        path('planificacion/delete/<int:pk>/', teachers.PlanificacionDelete.as_view(), name='planificacion_delete'),
        #end

        path('', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('ajax/load-indi/', teachers.load_indi, name='ajax_load_indi'),
        path('quiz/<int:quiz_pk>/student/', teachers.student, name='student'),
        path('quiz/pdf/<int:pk>', teachers.GeneratePdf.as_view(), name='generatepdf'),
        path('quiz/<int:pk>/mail/', teachers.mail, name='mail'),
        path('quiz/<int:pk>/send/', teachers.send, name='send'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/chart_data/', teachers.chart_data, name='chart_data'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('quiz/<int:pk>/tfquestion/add/', teachers.tfquestion_add, name='tfquestion_add'),
        path('quiz/<int:quiz_pk>/tfquestion/<int:tfquestion_pk>/', teachers.tfquestion_change, name='tfquestion_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
        path('quiz/<int:quiz_pk>/tfquestion/<int:tfquestion_pk>/delete/', teachers.TFQuestionDeleteView.as_view(), name='tfquestion_delete'),

django_school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.conf.urls import url

from django.contrib import admin
from classroom.views import classroom, students, teachers, fundacion, gestion, jefedepto

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classroom.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('accounts/signup/fundacion/', fundacion.FundacionSignUpView.as_view(), name='fundacion_signup'),
    path('accounts/signup/gestion/', gestion.GestionSignUpView.as_view(), name='gestion_signup'),
    path('accounts/signup/jefedepto/', jefedepto.JefeDSignUpView.as_view(), name='jefedepto_signup'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import (TemplateView,CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response


from django.views.defaults import page_not_found
 



class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:quiz_change_list')
        if request.user.is_student:
            return redirect('students:quiz_list')
        if request.user.is_fundacion:
            return redirect('fundacion:index')
        if request.user.is_jefedepto:
            return redirect('jefedepto:index')
        else:
            return redirect('gestion:indexg')
    return render(request, 'classroom/home.html')







  

classroom/views/gestion.py
import json
import traceback
from itertools import chain
from .__init__ import *
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import get_template,render_to_string
from django.utils.html import strip_tags
from django.template import Context
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.http import JsonResponse,HttpResponse, HttpResponseRedirect
from rest_framework.views import APIView
from rest_framework.response import Response
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, TemplateView, View)
from ..decorators import gestion_required
from ..forms import BaseAnswerInlineFormSet,QuestionForm, GestionSignUpForm,  CategoryForm, ColegioForm
from ..models import Answer, Question, Quiz, User, TakenQuiz, StudentAnswer, Category,  Colegios





class GestionSignUpView(CreateView):
    model = User
    form_class = GestionSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'gestion'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('gestion:indexg')


@method_decorator([login_required, gestion_required], name='dispatch')
class IndexListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'classroom/gestion/indexg.html'

    def get_queryset(self):
        gestion = self.request.user.gestion
        gestion_interests = gestion.interests.values_list('pk', flat=True)
        gestion_curso = gestion.curso.values_list('pk', flat=True)
        gestion_colegio = gestion.colegio.values_list('pk', flat=True)
        taken_quizzes = gestion.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.filter(curso__in=gestion_curso, subject__in=gestion_interests, colegio__in=gestion_colegio) \
            .exclude(pk__in=taken_quizzes) 
        return queryset

classroom/templates/classroom/students/_header.html
<div class="container-fluid">
<h2> <strong>Exámenes</strong>

  {% for colegio in user.student.colegio.all %}
  <img src=" {{ colegio.imagen.url }} " class="img-fluid" style="width: 18%; float: right;"/>
  {% endfor %}
</h2>
<p class="text-muted">
  Asignaturas:{% for subject in user.student.interests.all %} {{ subject.get_html_badge }}{% endfor %}
  
 {# <a href="{% url 'students:student_interests' %}"><small>(update interests)</small></a>  #} 
</p>
<p class="text-muted">Curso: {% for curso in user.student.curso.all %} {{curso}}{% endfor %}{% for nivel in user.student.nivel.all %} {% if nivel.id == 1 %} {{nivel}} {% else %} {% if nivel.id == 2 %} {{nivel}} {% else %}{% if nivel.id == 3 %} {{nivel}} {% else %}{% if nivel.id == 4 %} {{nivel}} {% endif %} {% endif %}{% endif %}{% endif %}{% endfor %}</p>
<p class="text-muted">Colegio: {% for colegio in user.student.colegio.all %} {{colegio.get_html_badge}}{% endfor %}</p>
</div>
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'students:quiz_list' %}">Nuevos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'students:taken_quiz_list' %}">Tomados</a>
  </li>
</ul>

classroom/templates/classroom/students/colegio_form.html
{% extends 'base.html' %}
<!--Formulario para editar el colegio-->
{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Modificar tu colegio</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Guardar cambios</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Cancelar</a>
  </form>
{% endblock %}

classroom/templates/classroom/students/curso_form.html
{% extends 'base.html' %}
<!--Formulario para editar el curso del alumno-->
{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Modificar tu Curso</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Guardar cambios</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Cancelar</a>
  </form>
{% endblock %}

classroom/templates/classroom/students/interests_form.html
{% extends 'base.html' %}
<!--Formulario para editar las asignaturas-->
{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Modificar tus asignaturas</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Guardar cambios</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Cancelar</a>
  </form>
{% endblock %}

classroom/templates/classroom/students/quiz_info.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<!--Información del examen a tomar-->

<div class="container-fluid" style="text-align: center, justify">
        <h2 class="text-center"><strong>{{ quiz.name }}</strong></h2> 
        <br>
        <p class="mb-3"><strong>Profesor: </strong> {{ quiz.owner.first_name }} {{ quiz.owner.last_name }}</p> 
        <p class="mb-3" style="float: right;" ><strong>Curso: </strong> {{ quiz.curso }}</p>    
        <p class="mb-3"><strong>Puntos:</strong> {{quiz.max_score}}</p> 

        <br>
        <div class="card border-dark ">
                <div class="card-body">
                        <strong>Instrucciones:</strong>
                        <br>
                        <br>
                        <p class="text-justify" style="white-space: pre-wrap; ">{{ quiz.description }}</p>
                        <pre style="font-family: Arial, Helvetica, sans-serif"></pre>
                </div>

        </div>


</div>

<br>
<a id="shortlyStart" href="{% url 'students:take_quiz' quiz.pk  %}" class="btn btn-primary">Siguiente →</a>

{% endblock %}

classroom/templates/classroom/students/quiz_list.html
{% extends 'base.html' %}
<!--Vista de las pruebas que el alumno puede tomar-->
{% block content %}
  {% include 'classroom/students/_header.html' with active='new' %}
  <div class=" table-responsive table-sm ">
    <table id="example" class="table table-bordered display  ">
      <thead>
        <tr>
          <th class="text-center">Examen</th>
          <th class="text-center">Asignatura</th>
          <th class="text-center">Profesor</th>
          <th class="text-center">Preguntas</th>
          <th></th>
        </tr>
      </thead>
      <tbody >
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle text-center">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle text-center">{{ quiz.owner.first_name }} {{ quiz.owner.last_name }}</td>
            <td class="align-middle text-center">{{ quiz.questions_count }} Preguntas</td>
            <td class="text-center">
              <a href="{% url 'students:quiz_info' quiz.pk %}" class="btn btn-primary">Comenzar Examen</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No hay examenes que puedas tomar en este momento.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

classroom/templates/classroom/students/take_quiz_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

  <!--Barra de progreso-->
  <div class="progress mb-3">
      <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
    </div>
  <!--Cronometro-->
    <div class="mb-3" id="defaultCountdown" ></div> <br>

    <h4 class="mb-3">{{ quiz.name }}</h4>

    <hr>
<br>
  {% if question.texto == False %}
  <p></p>
  {% else %}
  {% if question.texto %}
  <div  class="border border-dark">
      <br>
      <div class="container">
        <div>

            <h3 class="text-left">{{question.texto}}</h3>
            <h4> {{question.texto.subtitulo}} </h4>
            <p class="text-justify" style="white-space: pre-wrap; ">{{question.texto.texto}}</p>

            <br>

        </div>
        </div>
      <br>
    </div>
{% endif %}
{% endif %}

<div  class="border border-dark">
  <br>
  <div class="container">

    <h4 class="lead"> <strong>{{question.number}}.-  {% if question.pregunta %} {{question.pregunta}} {% else %} {{ question.text }} {% endif %} ({{ question.puntaje}} puntos)</strong></h4>

        {% if question.description %}
      <h5 class="lead">{{ question.description }} </h5>
      {% endif %}


      <!--Audio de la pregunta-->
      {% if question.document == 'False' %}
      {% else %}
        {% if question.document  %}
        <audio controls='controls'>
          <source src="{{ question.document.url }}" type="audio/mpeg">
        </audio>

        {% endif %}
      <p></p>
      {% endif %}
    {% if question.video == 'False' %}
      <p></p>

      {% else %}
      {% if question.video %}
      <video width="320" height="240" controls='controls'>
        <source src="{{ question.video.url }} " type="video/mp4">
      </video>
      {% endif %}
      {% endif %}
      {% if question.image == 'False'  %}
      <p></p>

      {% else %}
      {% if question.image %}
      <br>
      <a href="{{ question.image.url }}" target="_blank"><img src="{{ question.image.url }}"  class="img-fluid border border-dark float-md" style="width: 25%;"/></a>

      {% endif %}
      <br>
      {% endif %}
      <br>
    <!--
      {% if question.url %}
      <iframe width="420" height="315" src="https://www.youtube.com/embed/{{question.url}}" frameborder="0" allow="encrypted-media" allowfullscreen></iframe>
      {% else %}
      {% endif %}
    -->
      <form method="post" name="takenquiz" id="takenquiz" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary redirect"  >Siguiente →</button>
      </form>
      <br>
  </div>
    <br>
</div>










  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!--Función java del cronometro-->
<script>

    function getCookie(name) {
      var value = "; " + document.cookie;
      var parts = value.split("; " + name + "=");
      if (parts.length == 2) return parts.pop().split(";").shift();
    }

    function cookieExists(name){
      if(document.cookie.indexOf(name+'=')==-1){
        return false;
      }
      else{
        return true;
      }
    }

    var time = {{ timeQ }};
    if(cookieExists('time')){
      time=getCookie('time')/60;
    }


  $(function () {

    newYear = new Date();
    newYear.setSeconds(newYear.getSeconds() + time*60);
    $('#defaultCountdown').countdown({until: newYear, onExpiry: liftOff,onTick: timeset});

    function timeset() {
      var tarra=$('#defaultCountdown').countdown('getTimes');
      var count=0;
      for (let i = tarra.length-1; i > -1; i--) {
        count = count + (tarra[i] *(60**((tarra.length-1)-i)));
      }
      document.cookie = "time="+count;
    };



    function liftOff() {
      document.cookie = "time= ; expires = Thu, 01 Jan 1970 00:00:00 GMT";//delete cookie
      alert('El Examen ah terminado! Una vez respondas esta última pregunta terminara el examen.');

    }

  });





</script>
{% endblock %}

classroom/templates/classroom/students/taken_quiz_list.html
{% extends 'base.html' %}
<!--Vista de las pruebas que el alumno tomo-->
{% block content %}
  {% include 'classroom/students/_header.html' with active='taken' %}
  <div class="table-responsive">
    <table id="example" class="table table-bordered  display table-sm">
      <thead>
        <tr>
          <th class="text-center">Examen</th>
          <th class="text-center">Asignatura</th>
          <th class="text-center">Profesor</th>
          <th class="text-center">Nota</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_quiz in taken_quizzes %}
          <tr>
            <td class="text-center">{{ taken_quiz.quiz.name }}</td>
            <td class="text-center">{{ taken_quiz.quiz.subject.get_html_badge }}</td>
            <td class="text-center">{{taken_quiz.quiz.owner.first_name }} {{ taken_quiz.quiz.owner.last_name }}</td>       
            <td class="text-center" ><span class="{% if taken_quiz.score < 3.99 %} badge badge-danger {% else %} {% if taken_quiz.score >= 4.0 and taken_quiz.score < 4.95 %} badge badge-success  {% else %}{% if taken_quiz.score >= 4.95 %}badge badge-primary {% endif %} {% endif %} {% endif %}">{{ taken_quiz.score }}</span></td>           

          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">No has realizado ningun examen todavia</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>


{% endblock %}